// This file was auto-generated by `tool/generate_test_entrypoints.dart`.
// ignore_for_file: avoid_print
import 'package:test/test.dart';

import 'integration_test.dart' as integration_test;
import 'sync_manager_test.dart' as sync_manager_test;
import 'syncable_database_test.dart' as syncable_database_test;

void main() {
  group(
    'integration_test.dart: ',
    integration_test.main,
  );
  group(
    'sync_manager_test.dart: ',
    sync_manager_test.main,
  );
  group(
    'syncable_database_test.dart: ',
    syncable_database_test.main,
  );
}
