name: syncable
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  drift: ^2.26.0
  logging: ^1.3.0
  supabase: ^2.6.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  equatable: ^2.0.7
  http: ^1.3.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  lint: ^2.7.0
  lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.24.0
  uuid: ^4.5.1
